### ISSUE TITLE
Action to recalculate taxes

### ISSUE THREAD

**Issue by thenbrent** [Prospress/automatewoo-subscriptions#12]
While it's possible to add/update/remove taxes, I think it makes more sense to start out tax modifications with a single _Reculate taxes_ action that applies the store's current settings to the subscription. This more closely matches the built-in WooCommerce behaviour, and also fits the most likely use case of updating Subscriptions to align with changes to taxes already set up on the store.

**Comment by danbitzer** [comment]
I have removed the following line from the [Other bulk updates](https://automatewoo.com/docs/examples/bulk-update-subscription-prices/#other-bulk-updates) section:
"Tax amounts, in case your country, state or city changes its sales taxes rates or titles"

This can be re-added when this action is added.

**Comment by danbitzer** [comment]
I've opened an idea so we can track the popularity of this feature: https://ideas.automatewoo.com/automatewoo/p/action-to-recalculate-taxes-on-subscriptions

**Comment by thenbrent** [comment]
I started work on this a while back. I've pushed my WIP changes to https://github.com/Prospress/automatewoo-subscriptions/commit/b9980f5bf21f15db08abab7d8181979c6573027b. That work may or may not be helpful for implementing this.

**Comment by mbruschi** [comment]
Today Germany introduced a 16% tax rate for the next 6 months and we need to change the 19% tax to 16% on all subscriptions from German customers without VAT ID. If I understand it correctly, that's not yet possible and this action would be needed right?

btw: It looks like other countries in Europe are to follow.

**Comment by danbitzer** [comment]
@mbruschi we now have an open PR (#50) to add this feature. I hope to get a release out in the next day or two.

**Comment by mbruschi** [comment]
Don't know if I should report this as a new issue or post on this one? Anyways, seems like the taxes are recalculated correctly, however, the recalculation doesn't apply the new description of the taxes.

Our workflow does recalculate the taxes before renewal. The tax rate for Germany has dropped from 19% to 16% and so have the label and descriptions thereof. The calculations are right (7.56*1.16=8.77) but the label is not updated and still says 19%.

![image](https://user-images.githubusercontent.com/6988573/88194747-75d32800-cc3f-11ea-8a34-fcc3d937510b.png)

**Comment by JPry** [comment]
@mbruschi 

> seems like the taxes are recalculated correctly, however, the recalculation doesn't apply the new description of the taxes.

If you manually recalculate taxes using the native WC interface, do you see the same behavior? Or does that only happen with an AutomateWoo action?

**Comment by mbruschi** [comment]
@JPry I just looked into it and yes. To achieve the expected result I have to click on the `x` you see there on the screenshot to remove the tax and then hit `Recalculate` which adds the 16% tax with the right label. Is there an action `Remove tax` that could be triggered before doing `Recalculate tax` in the workflow?

**Comment by danbitzer** [comment]
@mbruschi when I try this on my site I don't see any percentage in the label. Do you have an extension or some custom code that adds the percentage to the tax label?

**Comment by mbruschi** [comment]
@danielbitzer it could be that this only comes with [the VAT plugin](https://www.simbahosting.co.uk/s3/product/woocommerce-eu-vat-compliance/). Anyway, I ended up solving it with a custom function which before recalculating the taxes removes them.

```php
function wp_automatewoo_reset_taxes( $workflow ) {
	$subscription = $workflow->data_layer()->get_subscription();
	if ( ! $subscription ) {
		return;
	}

	foreach ( $subscription->get_items( 'tax' ) as $item_id => $item ) {
		$subscription->remove_item( $item_id );
	}

	$subscription->save();
	$subscription->calculate_totals( true );
	$subscription->add_order_note(
		sprintf(
			__( '%1$s workflow run: recalculate taxes. (Workflow ID: %2$d)', 'automatewoo' ),
			$workflow->get_title(),
			$workflow->get_id()
		),
		false,
		false
	);
}
````

**Comment by danbitzer** [comment]
@mbruschi Ok that makes sense. Thanks for letting us know!

**Comment by danbitzer** [comment]
Note: I've opened an issue in WooCommerce core to hopefully fix the issue where tax names are not updated when recalculating taxes: https://github.com/woocommerce/woocommerce/issues/28649
