### ISSUE TITLE
Update Product Price field action can't take variables

### ISSUE THREAD

**Issue by zabishop** [Prospress/automatewoo-subscriptions#16]
Screen cast: http://pic.pros.pr/6a95c6d4da2a.

In response to this https://secure.helpscout.net/conversation/818834832/29911?folderId=2459294

Customer is trying to pass a variable as the price.  

The bug, in my opinion, is either:

A). Variables should be accepted.  If so, the fix which might have broader implications, i.e. all strings may have to be passible.  

B). At the minimum, some kind of validation / error messaging should be reported to the customer.

**Comment by zabishop** [comment]
@thenbrent Just tagging you so it comes up on your radar.

**Comment by thenbrent** [comment]
Closing in favour of https://github.com/Prospress/automatewoo/issues/208
