### ISSUE TITLE
Allow the trigger for pending cancelation as well as active status.

### ISSUE THREAD

**Issue by berkmh** [Prospress/automatewoo-subscriptions#20]
When using the workflow described on pre-paid subscriptions, there should be an option to allow on pending-cancelation as well as active status. This allows store owners to continue sending products to consumers who only want 1 pre-paid term and do want a renewal to occur so they cancel right after subscribing. This is a common occurrence with subscription businesses and should be addressed.

**Comment by thenbrent** [comment]
Hi @berkmh. Renewal orders cannot be created when a subscription has the _Pending Cancellation_ status. That limitation is part of WooCommerce Subscriptions. It's not a limitation AutomateWoo can easily overcome (yet). There are a few options for handling cancellation in the doc here: https://automatewoo.com/docs/examples/pre-paid-subscriptions/#subscription-cancellation

None of those are great options, and we hope to eventually have better options available, like actions to process renewals, but for now, that's the best available. :)
