### ISSUE TITLE
Custom schedule / force end or renewal based on date (and other tricks)

### ISSUE THREAD

**Issue by renansavidan** [Prospress/automatewoo-subscriptions#25]
Hi,
I purchased WooCommerce Subscription but I have special needs not covered yet it seems.
What I have imagined for my client's website is : 

For registration [part 1] :
New subscriber gets a personalized pricing each month (based on his/her income input on the checkout page and the remaining month in the year) / I am taking care of this customization already with other freelancers. It is not tested yet but I assume that if I can update the order on the checkout screen when the customer purchases the recalculated pricing will apply.

For renewal [part 2] : 
1 - At the end of the civil year, 31st of December each year I need to "force" the end of the subscription.
2 - As the subscription is ended people must renew online, they get emailed as a normal WooCommerce Subscription process and we are back to the [part 1] (but this time based on 12 month calculation)

So far I can't find a way to schedule an end for the subscription so people have to login and enter their new incomes for the next year subscription.
I purchased AutomateWoo as well but still stuck.
I just read on your doc you are working on the feature that could save me (and my client).
I mean if I am able to bulk trigger the  end of all subscription the 31st of December each year then subscribers will have to login and I could use my customized code when they re-purchase the product (or renew, I don't really know how to call it)

Can you help with that ? Is there a way to do it ?
Can you provide some code ?
To be honest I have been working on this feature for weeks almost - I opened several tickets with WooCommerce support, AutomateWoo... and I still can't make it.
I already came to the "solution" to customize pricing on registration (full yearly amount and monthly payements) but it is not enough as the product  I am working on require a re-adjustment every new year.
Thank you in advance,
best regards,
Renan Savidan.

**Comment by renansavidan** [comment]
Hi guys.
I think this issue is a bit a duplicate of another one - sorry if I pollute the threads.
#Action to Update Dates (or additional fields on the Update Schedule action) #3 
Anyway I am desperately looking for a way to make it work. Any help appreciated really.

**Comment by NickGreen** [comment]
Hello @renansavidan Since this is a support request,I'm going to close this now, so it can be dealt with through our support platforms.
