### ISSUE TITLE
Subscription - Update Product action does not correctly display prices with comma decimal separator

### ISSUE THREAD

**Issue by jessLundie** [Prospress/automatewoo-subscriptions#28]
## Synopsis
The _Subscription - Update Product_ action will not correctly display saved _Custom product price_ in a workflow when the store has their currency settings set to use a comma as the _Decimal separator_ and a period as the _Thousand separator_. The price *is* correctly saved in the database based on the site's currency settings. 

## Ticket
zd-2205509

## Expected v. Actual
Expected: Prices would display correctly based on store's currency settings.

Actual: Prices are saved to the databse correctly, but then display based on default US currency settings where _Decimal separator_ is a period.

## Steps to Replicate
1. Go to **WooCommerce > Settings > General** - _Currency Options_ and set them as shown here: [https://cld.wthms.co/DW64Yv](https://cld.wthms.co/DW64Yv)
2. Create a workflow using _Subscription - Update Product_ action
3. Set any price and save workflow: [https://cld.wthms.co/iLWgcx](https://cld.wthms.co/iLWgcx)
4. See that price is not displaying correctly after saving: [https://cld.wthms.co/lQ8e7J](https://cld.wthms.co/lQ8e7J)
5. Price is saved correctly in the database: [https://cld.wthms.co/Vedvyc](https://cld.wthms.co/Vedvyc)

**Comment by thenbrent** [comment]
Thanks for the amazing bug report @jessLundie!

@danielbitzer I think this will need to be fixed in `AutomateWoo\Fields\Price` in AW core. Will it be fixed by implementing the `render()` method with something like this?

```php
function render( $value ) {
	$value = wc_format_localized_price( $value );
	parent::render( $value );
}
```

**Comment by danbitzer** [comment]
Thanks for the bug report @jessLundie and thanks @thenbrent for the fix suggestion!

I've opened a PR in AutomateWoo core to address this and any other localized pricing issues in AW core https://github.com/Prospress/automatewoo/pull/270
