### ISSUE TITLE
Can only update subscriptions up to a certain date 

### ISSUE THREAD

**Issue by hoobsi** [Prospress/automatewoo-subscriptions#32]
Hi there, 

My problem is probably site related:

I am trying to update: 

- the currency (from Pounds to USD)
- the product with new totals
- the shipping rate

for many subscriptions that have been migrated to a new site. 

It worked very well with the "Manual Subscriptions Trigger" tool BUT only up to a certain date (July 10, 2019). This is coincidentally also the day on which the site was first launched and it somehow must be related?! 

We do have subscriptions (from the UK site) that were started before July 10th and transferred to this new site together with the other subscriptions. 

I need to update all subscriptions (preferably with the manual trigger) and am wondering if there is a way to manipulate the site's date or some other workaround? Perhaps it's also a different issue here... 

Thanks in advance! 
Michael

**Comment by thenbrent** [comment]
Hi @hoobsi, thanks for reporting. Can you please submit a support request for this via https://automatewoo.com/get-help/

Just include all of the above information and the support team will be able to investigate and help you out.
