### ISSUE TITLE
Trigger and bulk price update

### ISSUE THREAD

**Issue by neoseeyou** [Prospress/automatewoo-subscriptions#33]
Hello

I think it's not really an issue but more a feature request

I tried to achieve this scenario and unfortunatly it's not working after several tests

Let say a customer have 2 subscriptions: A and B

Subscription A contain product A1
Subscription B contain product B1 (premium subscription product who apply 5% off to other products)

I want to change the price of product A1 (only for this customer's subscription) if the status of his subscription B is changing from active to on hold/cancelled/...

In automatewoo i set like this

- Trigger: Subscription status changed - each line
Status change from: active
Status change to: on hold, cancel, expired
Subscription product: Product B1
Recheck status before run: yes

- No rules

- Actions: Update product
Product: Product A1
Custome product price: my new price.

The workflow start when i modify the status of subscription B but does not affect the price of product A1 in subscription A

Thank you

**Comment by neoseeyou** [comment]
Also i need to find a way to apply the price change on product A1 only to the current customer who change the subscription B status.

**Comment by JPry** [comment]
Hi @neoseeyou, thanks for reporting this. Can you please submit a support request for this via https://automatewoo.com/get-help/

Just include all of the above information and the support team will be able to investigate and help you out.

**Comment by neoseeyou** [comment]
Yes thank you !
