### ISSUE TITLE
Add 'Customer - Subscription Count' rule

### ISSUE THREAD

**Issue by jrick1229** [Prospress/automatewoo-subscriptions#34]
#### Idea already opened here: https://ideas.automatewoo.com/automatewoo/p/new-rule-customer-subscription-count

(feel free to close this if needed)

### Idea

Since we already have the option in AutomateWoo to use a `Customer - Order Count` rule, I didn't know how difficult it would be to just replace `get_order_count()` with `get_subscription_count()` in a semi-duplicated rule.

Since this is potentially easy to implement (I really don't know), I figured I'd open an enhancement issue to see thoughts.
Otherwise, I'm sure the idea on the Ideas board will suffice.

**Comment by danbitzer** [comment]
Thanks @jrick1229!

@JPry @jconroy what do you think about only having features tracked on the ideas board and closing feature request Github issues?

**Comment by findingsimple** [comment]
I think it's fine to leave features requests on the ideas board unless we're planning/starting work on something and need to discuss internal.

**Comment by danbitzer** [comment]
I just noticed this issue is on the AW Subscription add-on. I'm closing since I'd prefer to add this to core. We'll rely on [the idea](https://ideas.automatewoo.com/automatewoo/p/new-rule-customer-subscription-count) to track this feature.
