### ISSUE TITLE
Subscription - Update Schedule action will not save with `No change` in Billing Interval field

### ISSUE THREAD

**Issue by jessLundie** [Prospress/automatewoo-subscriptions#35]
### Issue
The _Subscription - Update Schedule_ action offers `No change` as placeholder text for _Billing Interval_. However, when you save the workflow, this field requires a number input. 

### Steps to Replicate
1. Create a workflow with _Subscription - Update Schedule_
2. Try to save the workflow with no value in the _Billing Interval_ field
3. No go - that field must have a non-zero numerical value

![https://cld.wthms.co/tKJjg5](https://cld.wthms.co/tKJjg5+)
Full Image: https://cld.wthms.co/tKJjg5+

### Expected
Is this expected / intended? If so, I'd suggest changing the placeholder language. The placeholder language led me to expect that a null or `No change` value would be a viable option for this field.

**Comment by danbitzer** [comment]
Good point! That would be because the field has been set as a `required` field. I'll open a PR to change that.

**Comment by sudheepcp2020** [comment]
Can't see workflow with Subscription - Update Schedule in the add action while creating workflow

**Comment by sudheepcp2020** [comment]
Anybody can help me

**Comment by jessLundie** [comment]
Hi @sudheepcp2020 - The Subscription - Update Schedule action will only appear in your available actions list if you are using a Subscriptions trigger. Order triggers, for example, won't have this as an option. First, double check that you are using a Subscriptions trigger in your workflow.

If you still aren't seeing this action while using a subscriptions trigger and you have an active license for AutomateWoo, please go ahead and open an AutomateWoo ticket with us at WooCommerce.com. This is a free add-on for the paid plugin, so we'll be more than happy to assist you there!

**Comment by sudheepcp2020** [comment]
Hi
I am using Subscriptions trigger and worked fine in dev site. but in live
site that option is not listing. Is there any configurations need to be
done in backend? Can you help me with live chat, as I am ready to share my
screen as well.

Can you please send me the link to create a ticket at WooCommerce?

Thanks
Sudheep

**Comment by jessLundie** [comment]
Hi @sudheepcp2020,

We'll be able to assist with this in live chat if a support engineer is available. If not, you'll be rerouted to a ticket and we'll respond via email. 

First, log in to the WooCommerce.com account that holds your AutomateWoo license. Then go to https://woocommerce.com/my-account/create-a-ticket/?form=ticket and select AutomateWoo in the **I need help with** dropdown: https://cld.wthms.co/6NYfit

**Comment by sudheepcp2020** [comment]
Hi,
 Thanks for your response. I created a ticket above said url. Can you
please give me a support engineer as its urgent for me to resolve
this issue at the earliest in live version.

 Thanks
Sudheep

**Comment by sudheepcp2020** [comment]
Hi
 Any update on this

**Comment by jessLundie** [comment]
Thanks for submitting that ticket, @sudheepcp2020! I was able to locate the two tickets you submitted in our queue. We strive to respond to tickets within 24 hours, but are experiencing a significant backlog of support requests due to Covid so it may be a bit longer than that. We appreciate your patience while we do our best to catch up!

In the meantime, no need to submit any additional tickets. We'll merge the two that you've submitted so far so that we can keep all information in a single location.

**Comment by sudheepcp2020** [comment]
Hi,
 appreciate your quick response; I have no other tickets, but the existing
ticket is most urgent for me. I have been stopped with this issue for 2
days.
 Again thanks
Sudheep
