### ISSUE TITLE
Not possible to translate "for x months" string

### ISSUE THREAD

**Issue by grig-23** [Prospress/automatewoo-subscriptions#37]
**Reported in:**

2663975-zen

**Summary of an issue:**

"For X months" part cannot be translated:

![Screenshot](https://d.pr/i/pg3VWe+)
Screenshot direct link: https://d.pr/i/pg3VWe

I found the first part in Loco Translate:

![Screenshot](https://d.pr/i/XyPslZ+)
Screenshot direct link: https://d.pr/i/XyPslZ

The second part doesn't seem to be translatable.

WPML support informed this customer about this:

> I wasn't able to find a way to translate the months part. It seems that this is a variable that comes from WooCommerce Subscriptions plugin. I dig into the plugin code and found the source of the string but I wasn't able to find a way to translate it.

**Steps to replicate:**

1. Install Loco Translate
2. Search for "Months"
3. This particular part of the string can't be translated.

**Comment by grig-23** [comment]
Update:

This change took quite a while to manifest itself on my product page:

![Screenshot](https://d.pr/i/hVZRew+)
Screenshot direct link: https://d.pr/i/hVZRew

I've changed it once again (added "changed") and I still don't see the result.

Not too sure whether this bug report has to be closed, investigating further.

**Comment by grig-23** [comment]
The string can be adjusted using this plugin:

https://github.com/woocommerce/woocommerce-subscriptions-custom-price-string

It looks like translation combinations are stored in a transient, this is why changes aren't reflected immediately.

Closing

**Comment by danbitzer** [comment]
Hi @grigorijurasov, that string is in the WooCommerce Subscriptions plugin. Repo: https://github.com/woocommerce/woocommerce-subscriptions/
