### ISSUE TITLE
Add "update all subscriptions" checkbox during failed payment checkout

### ISSUE THREAD

**Issue by FreshPhil** [Prospress/automatewoo-subscriptions#38]
When updating your payment method from **My Account > Payment Methods** there is a checkbox that allows you to use that payment method for all active subscriptions:

![](https://d.pr/i/0MQjwq+)
Image Link: https://d.pr/i/0MQjwq

For consistency, it would be great if we added the same option to the checkout page, when a customer is making a payment for a failed subscription.

2668557-zen
[Slack thread](https://a8c.slack.com/archives/CJTS771PB/p1580309625071500)

**Comment by findingsimple** [comment]
Hi @FreshPhil - this might be better suited to https://github.com/woocommerce/woocommerce-subscriptions/ if I'm understanding the background correctly

**Comment by amandasjackson** [comment]
@jconroy  and @FreshPhil  I moved it since I needed it for a ticket :)
 https://github.com/woocommerce/woocommerce-subscriptions/issues/3609

**Comment by FreshPhil** [comment]
@jconroy - Yep, sorry about that. Accidentally was in the wrong Repo :|
