### ISSUE TITLE
Rule "Subscriptions - Item Category" not triggering email

### ISSUE THREAD

**Issue by yukikatayama** [Prospress/automatewoo-subscriptions#39]
2700698-zen

When the rule includes a subscriptions with a category, the workflow is not triggered:

<img width="1880" alt="Screen Shot 2020-02-13 at 12 45 00" src="https://user-images.githubusercontent.com/24614608/74463269-99f43700-4e5f-11ea-865e-501fcddbf730.png">

As a workaround, user has specified the sub product in the rule, instead of the category. 

Confirmed issue on AW 4.8.1 and Subs add-on 1.0.1

**Comment by danbitzer** [comment]
Thanks for the bug report @yukikatayama! I have opened a PR to fix the issue in the core AutomateWoo repo: https://github.com/woocommerce/automatewoo/pull/406

**Comment by danbitzer** [comment]
Will be fixed in AutomateWoo core version 4.8.2
