### ISSUE TITLE
'subscription remove shipping' - all shipping methods removes no shipping methods

### ISSUE THREAD

**Issue by WillBrubaker** [Prospress/automatewoo-subscriptions#45]
Reported in #2839811-zen

These actions are configured for a workflow:
![see screen shot](https://d.pr/i/Q5bDzv+)

The workflow ran, but the shipping was not removed from the subscription.

I tested this locally and the same behavior happens. However, if I specify a shipping method to remove and the subscription has that shipping method, then it does work as expected.

**Comment by layoutd** [comment]
Thanks for the report @WillBrubaker! We've been able to replicate the issue and have opened PR #46 to address the problem.
