### ISSUE TITLE
Incorrect subscription order total with update product actions and Recurring Product discount coupon

### ISSUE THREAD

**Issue by pokhiii** [Prospress/automatewoo-subscriptions#52]
I have used the `Update Product` Action to update the product price on the Manual Subscription data type workflow.
Earlier my subscription total was this:
![image](https://user-images.githubusercontent.com/11808845/89789664-8429ab00-db3e-11ea-86bc-f2dfb8e5c024.png)
and after running the workflow, the price get updated but the coupon amount doesn't get deducted from the subscription
![image](https://user-images.githubusercontent.com/11808845/89789731-9ad00200-db3e-11ea-92da-55f489cc2cdb.png)

Coupon discount type is `Recurring Product discount` with no limit.

#### Expected results:
|Items Subtotal:  |    $ 180.00 |
|---  |    --- |
|     Coupon(s):  |    -$ 31.08 |
|      Shipping:  |    $  0.00 |
|   Order Total:  |    $148.92 |

**Comment by findingsimple** [comment]
Hi @abhishek-pokhriyal 👋 Thanks for taking the time to open an issue. Based on your steps I tried to reproduce the coupon being removed but I was unable to replicate. Screenshot below shows my coupon was still applied after updating the subscription product (and workflow order note is present to indicate the workflow ran successfully).

![Screen Shot 2020-08-11 at 4 56 33 pm](https://user-images.githubusercontent.com/355014/89869662-d1b41f80-dbf3-11ea-9cde-77447ce67ce4.png)

We don't provide support for AutomateWoo or WooCommerce Subscriptions directly via this repository/github so I'd recommend [opening a ticket on WooCommerce.com](https://woocommerce.com/my-account/create-a-ticket/) and one of our support staff will be able to help you investigate the issue more deeply.

**Comment by pokhiii** [comment]
Hi @jconroy, thanks for the quick response. It seems like the issue occurs when the subscriptions are created by a cart-level subscription plan offered by [WooCommerce All Products For Subscriptions](https://woocommerce.com/products/all-products-for-woocommerce-subscriptions/). I've written to their support to investigate the issue.
