### ISSUE TITLE
Subscription stays inactive. Looking for a version 4.8 which I cannot find

### ISSUE THREAD

**Issue by marceleste** [Prospress/automatewoo-subscriptions#56]
![Screenshot 2020-11-16 at 22 48 42](https://user-images.githubusercontent.com/8586732/99306769-4be0e980-285e-11eb-92c4-3e3df3a74c29.png)

**Comment by danbitzer** [comment]
@marceleste 4.8 was released almost a year ago. You can get the latest version (5.1.2) of AutomateWoo via WooCommerce.com: https://woocommerce.com/products/automatewoo/
