### ISSUE TITLE
Undefined $shipping_data variable in Action_Subscription_Add_Shipping::get_note

### ISSUE THREAD

**Issue by danielbitzer** [Prospress/automatewoo-subscriptions#57]
PHPstorm analyzer found this: https://github.com/woocommerce/automatewoo-subscriptions/blob/1546030d6e93f7bfcdb82a3f9fd21667b66c47e2/includes/actions/add-shipping.php#L89-L91

**Comment by nima-karimi** [comment]
Merged #61 so this should be fixed in the next release (1.2.2)
