### ISSUE TITLE
Activating the AW Subscriptions add-on does not display welcome notice

### ISSUE THREAD

**Issue by ecgan** [Prospress/automatewoo-subscriptions#58]
When we activate the AutomateWoo Subscriptions add-on and then go to the AutomateWoo dashboard, there should be a welcome notice with a getting started guide, but there isn't one. 

This issue is part of 789-gh-woocommerce/automatewoo. It is related and similar to 84-gh-woocommerce/automatewoo-referrals which has been fixed in PR 91-gh-woocommerce/automatewoo-referrals and 845-gh-woocommerce/automatewoo. 

The expected result should be similar to below:

![image](https://user-images.githubusercontent.com/417342/99822756-90d28c00-2b8e-11eb-8045-b6fa84e19d4d.png)

**Comment by ecgan** [comment]
@jconroy @danielbitzer ,

I looked into this AW Subscriptions code base and it is quite different from AW Referrals and AW Birthdays. It does not extend from AutomateWoo base class. It does not have a `get_getting_started_url` function. I'm guessing it didn't have a welcome notice in the first place? How should we proceed with this?

**Comment by findingsimple** [comment]
> When we activate the AutomateWoo Subscriptions add-on and then go to the AutomateWoo dashboard, there should be a welcome notice with a getting started guide, but there isn't one.

I forgot this extension isn't treated quite like the other "add-ons" - the original issue identified within the AW repo (quoted below for reference) is related to the license key system which this plugin hasn't interacted with.

> Previously the add-on welcome notice was displayed after the user entered a license key. Now we don't have any restrictions if the license key is missing and the welcome notice will only be displayed if using the legacy license system.

There also is no getting started guide doc for AW Subscriptions Add-ons, so there won't be a similar notice.

> I'm guessing it didn't have a welcome notice in the first place? How should we proceed with this?

If there are no relevant notices then I don't think we need to do anything here. Thanks for exploring - I'd forgot this extension didn't quite work like the others
