### ISSUE TITLE
WC 5.0 - Increase tested up to tags

### ISSUE THREAD

**Issue by findingsimple** [Prospress/automatewoo-subscriptions#65]
WooCommerce 5.0 is currently scheduled for release on February 9th.

With 5.0, WooCommerce is moving to WP versioning and 5.0 is no longer considered to include breaking changes.

Prior to 4.9.2, WooCommerce included a number of extra warnings to prep users for a major change. These are no longer necessary.

If WooCommerce users upgrade to 5.0 from a version prior to 4.9.2 they would still see these warnings.

To help avoid confusion and smooth the process we should be sure to perform the following...
* [x] Quick smoke test of functionality (review docs for functionality and intended usage)
* [x] Increase tested up to tags
* [x] Create follow-up issues for anything that needs to be fixed/investigated (or simply fix) - [generally we should be fine, the compact checks have come back](https://woocommercep2.wordpress.com/2021/01/23/woocommerce-5-0-compatibility-check/) ✅

**Comment by danbitzer** [comment]
I've done some testing of the add-on with WC 5.0, WC Subscriptions 3.0.13, AW 5.3-rc.1. Everything seems to be ok.
