### ISSUE TITLE
Trouble installing 

### ISSUE THREAD

**Issue by weisbart** [Prospress/automatewoo-subscriptions#8]
Added the plugin to my WooCommerce install (that has Automatewoo installed already). 

Got:

```
Fatal error: Uncaught Error: Call to undefined method PP_Dependencies::is_automatewoo_active() in /nas/content/live/recessdev/wp-content/plugins/automatewoo-subscriptions/automatewoo-subscriptions.php:51
Stack trace:
#0 /nas/content/live/recessdev/wp-admin/includes/plugin.php(1909): include()
#1 /nas/content/live/recessdev/wp-admin/plugins.php(172): plugin_sandbox_scrape('automatewoo-sub...')
#2 {main} thrown in /nas/content/live/recessdev/wp-content/plugins/automatewoo-subscriptions/automatewoo-subscriptions.php on line 51
```

**Comment by thenbrent** [comment]
Hi @weisbart thanks for the report and sorry for the trouble. This issue is fixed with https://github.com/Prospress/automatewoo-subscriptions/pull/9, which will be included in an initial beta version which I'll be tagging today.

**Comment by weisbart** [comment]
Hey @thenbrent thanks for the fix! 

Not sure if I should file this as a bug but...

I'm charging folks for an annual subscription up front, then swapping out the annual for a monthly subscription with a $0 charge using woo automate and this plugin so that I can ship them monthly subscription boxes. Trouble is it doesn't appear to trigger any actions UNLESS I bill $0.01 or more.

Happy to email you more info (with links to the workflows in question) if this does in fact sound like a bug to you.

**Comment by thenbrent** [comment]
Hi @weisbart, yes please send through a support ticket so we can help: https://automatewoo.com/get-help/

What you are attempting to do is planned as a supported use case, and we have a draft guide on how to do it, so it will be very helpful to share that with you and also for us to see how you set it up yourself (as well as resolve the issue with the trigger not firing of course). :)
